PennyLaneAI/plugin-test-matrix

- .github/workflows/braket-latest-latest.yml
- .github/workflows/braket-latest-stable.yml
- .github/workflows/braket-stable-latest.yml
- .github/workflows/braket-stable-stable.yml
- README.md
- compile.py
Consider the errors from the Braket device: (shown in https://github.com/PennyLaneAI/plugin-test-matrix/pull/4).
There are two PRs to fix the wires and probabilities-based errors:
https://github.com/aws/amazon-braket-pennylane-plugin-python/pull/55
https://github.com/aws/amazon-braket-pennylane-plugin-python/pull/56
However, the sampling based errors still remain. Specifically, we get an error for `test_no_0_shots` because the Braket device does not raise an error when 0 shots are specified. In fact, specifying 0 shots is the method to make the device become analytic.
Also, we get an error for the `TestSample` and `TestTensorSample` tests when `shots` is unspecified. This is because the shots defaults to zero (analytic mode), but we then ask the braket SDK to perform sampling with zero …
> Turn off tests related to sampling when shots=0 in the Braket device

- .github/workflows/forest-latest-latest.yml
- .github/workflows/forest-latest-stable.yml
- .github/workflows/forest-stable-latest.yml
- .github/workflows/forest-stable-stable.yml
- compile.py
We pin the Pyquil version to pyquil==2.28.2, because we do not support Pyquil 3.0. As it is pinned in the forest plugin, we could now find bug not related to the 3.0 version.
> Pin Pyquil version in the workflow

- .github/workflows/qiskit-latest-latest.yml
- .github/workflows/qiskit-latest-stable.yml
- .github/workflows/qiskit-stable-latest.yml
- .github/workflows/qiskit-stable-stable.yml
Some PennyLane Qiskit tests are not run because the env name of the token is not the same in the CI checks and in the plugin matrix, we replace `IBMQX_TOKEN` by `IBMQX_TOKEN_TEST`. 
We also remove IBMQ and runtime tests from the tests run, because using IBMQ can result in timeouts easily when using the CI.
> Change name IBMQ token env name and remove IBMQ/runtime tests

- .github/workflows/lightning-latest-latest.yml
- .github/workflows/lightning-latest-rc.yml
- .github/workflows/lightning-latest-stable.yml
- .github/workflows/lightning-stable-latest.yml
- .github/workflows/lightning-stable-stable.yml
Ubuntu 22.04 is required because GCC 10+ is needed for Lightning.
> Change ubuntu version for lightning

- .github/workflows/braket-latest-latest.yml
- .github/workflows/braket-latest-rc.yml
- .github/workflows/braket-latest-stable.yml
- .github/workflows/braket-stable-latest.yml
- .github/workflows/braket-stable-stable.yml
- compile.py
Braket [is failing](https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/5570471911/jobs/10187141436) because it [requires pytest-xdist](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/setup.cfg#L8) to be installed. We can install it everywhere, but I'm not sure if some plugins fail from multi-threading or not so I figured let's just start here.
> use pytest-xdist on braket

- .github/workflows/braket-latest-latest.yml
- .github/workflows/braket-stable-latest.yml
- README.md
- compile.py
- workflow-template-latest.yml
the errors hide meaningful results in the case of braket tests, so we should stop raising PL deprecation warnings as errors there.
I've added a mechanism to disable it for any plugin, by setting `no_deprecation_error` to `True` (or any value, really) in the plugin's definition in `compile.py`.
> do not raise deprecation warnings as errors on braket

- .github/workflows/qiskit-latest-latest.yml
- .github/workflows/qiskit-latest-rc.yml
- .github/workflows/qiskit-latest-stable.yml
- .github/workflows/qiskit-stable-latest.yml
- .github/workflows/qiskit-stable-stable.yml
- compile.py
After this, all the tests related to Qiskit should pass. I am 90% certain it doesn't need to be pinned anywhere else. 
This has been added to the shortcut story tracking all the things we need to put back when we release a plugin version compatible with 1.0.
> Pin Qiskit to 0.45.3

- .github/workflows/qiskit-latest-latest.yml
- .github/workflows/qiskit-latest-rc.yml
- .github/workflows/qiskit-latest-stable.yml
- .github/workflows/qiskit-stable-latest.yml
- .github/workflows/qiskit-stable-stable.yml
- README.md
- compile.py
- Run test matrix tests with Qiskit 1.0
- Run IBMQ tests with both Qiskit 0.45 and Qiskit 1.0
Confirmed in a fresh environment that I can `pip install pennylane` and the plugin and access the BasicSim device - not sure why the stable/latest tests can't find the device in the test matrix.
> Update test matrix to use Qiskit 1.0

- README.md
Adds a pass/fail badge for the new legacy opmath tests to the plugin matrix README
> Add Legacy opmath to the page

- .github/workflows/qiskit-latest-latest.yml
- .github/workflows/qiskit-latest-rc.yml
- .github/workflows/qiskit-latest-stable.yml
- .github/workflows/qiskit-stable-latest.yml
- .github/workflows/qiskit-stable-stable.yml
- README.md
- compile.py
The PL-Qiskit plugin no longer has tests that require an ibmq account. Namely `test_ibmq.py` and `test_runtime.py` have been deleted from the plugin CI tests and so are not relevant for the test matrix. This update accounts for the deletion of these tests and makes changes accordingly.
Related Issue:
[sc-69774]
> Update test matrix according to changes to PL-Qiskit plugin

- README.md
`qml`'s `update-dev` action now has a badge under the "QML repo" section.
> Add badge for `update-dev` action

- .github/workflows/aqt-stable-latest.yml
- .github/workflows/cirq-stable-latest.yml
- .github/workflows/ionq-stable-latest.yml
- .github/workflows/qiskit-stable-latest.yml
- .github/workflows/qulacs-stable-latest.yml
- .github/workflows/rigetti-stable-latest.yml
- workflow-template-latest.yml
As name says. Deprecated code present in the stable version of some plugins is causing deprecation warnings to be raised, which might cause other errors to be hidden, so I've updated the stable-latest tests to suppress even more pennylane deprecation warnings, specifically the `Tensor` deprecation.
> Suppress Tensor deprecation warnings in `stable-latest` tests

- .github/workflows/scripts/unique_warning_reporter.sh
- .github/workflows/workflow-wae-reporting.yml
- README.md
This PR adds support for a weekly report using updated data of the warnings as errors PR action in PennyLane. A table is added with the determined warnings (not dynamic due to no templated generation of markdown).
The table ie formatted as follows:
<table>
<tr>
<td><code>UserWarning</code></td>
<td><a href=https://github.com/PennyLaneAI/pennylane/actions/workflows/package_warnings_as_errors.yml><img src=https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2FPennyLaneAI%2Fplugin-test-matrix%2Frefs%2Ftags%2Fwae_data_tag%2Funique_wae.json&query=%24%5B0%5D.UserWarning&label=&color=9c6700></td>
</tr>
<tr>
<td><code>DeprecationWarning</code></td>
<td><a href=https://github.com/PennyLaneAI/pennylane/actions/workflows/package_warnings_as_errors.yml><img …
> Warnings as error reporting

- .github/workflows/aqt-latest-rc.yml
- .github/workflows/braket-latest-rc.yml
- .github/workflows/cirq-latest-rc.yml
- .github/workflows/ionq-latest-rc.yml
- .github/workflows/lightning-latest-rc.yml
- .github/workflows/qiskit-latest-rc.yml
- .github/workflows/qulacs-latest-rc.yml
- .github/workflows/rigetti-latest-rc.yml
- workflow-template-release-candidate.yml
Updating the Feature Freeze Testing Matrix on the plugin test matrix page to point to the upcoming release candidate. 
1) Currently, all the `{plugin}-rc / tests` checks are failing, because the `v0.40.0-rc0` PennyLane branch still has not been created. This will be created next week. For the timeline, I am simply following the steps in the recommended order reported [in the guidelines](https://github.com/PennyLaneAI/guidance-docs/blob/automate-pr-collection/development/pennylane-release.md#prepare-the-feature-freeze-test-matrix). In particular, the preparation of the Feature Freeze matrix is supposed to take place the week *before* feature freeze. That is, before the creation of the `rc` branch.
2) The `Ensure templates are not manually changed / check-diff (pull_request)` check is …
> Bumping `rc` version in plugins

- .github/workflows/lightning-latest-rc.yml
This PR fixes the issue that Lightning Kokkos was not installed due to missing a step to update the pyproject toml, resulting in failed test.
> Fix lightning-latest-rc kokkos failure

- .github/workflows/cirq-latest-latest.yml
- .github/workflows/cirq-latest-rc.yml
- .github/workflows/cirq-latest-stable.yml
- .github/workflows/cirq-stable-latest.yml
- .github/workflows/cirq-stable-stable.yml
`pip install cirq` is broken for Python3.10 due to the rigetti dependency having issues with the CRC of the compiled module.
Therefore, we perform the checks associated with `cirq` using `Python 3.11` instead.
[sc-85836]
> Switch from `Python 3.10` to `Python 3.11` for `Cirq`

- .github/workflows/aqt-latest-rc.yml
- .github/workflows/braket-latest-rc.yml
- .github/workflows/cirq-latest-rc.yml
- .github/workflows/ionq-latest-rc.yml
- .github/workflows/lightning-latest-rc.yml
- .github/workflows/qiskit-latest-rc.yml
- .github/workflows/qulacs-latest-rc.yml
- workflow-template-release-candidate.yml
Updating the Feature Freeze Testing Matrix on the plugin test matrix page to point to the upcoming release candidate. 
1) Currently, all the `{plugin}-rc / tests` checks are failing, because the `v0.41.0-rc0` PennyLane branch still has not been created. This will be created next week. For the timeline, I am simply following the steps in the recommended order reported [in the guidelines](https://github.com/PennyLaneAI/guidance-docs/blob/automate-pr-collection/development/pennylane-release.md#prepare-the-feature-freeze-test-matrix). In particular, the preparation of the Feature Freeze matrix is supposed to take place the week *before* feature freeze. That is, before the creation of the `rc` branch.
2) Notice that `cirq` is still tested with Python 11 instead of 10, due to the issue …
> Bumping version in plugins as preparation to PL 0.41 release

- README.md
This pull request updates the `README.md` file to include information about new V2 pipelines, alongside the existing V1 pipelines, for better documentation of CI workflows.
Documentation updates:
* Added a new "V2 Pipelines" section with links and status badges for `v2-build-branch-dev` and `v2-build-branch-master` workflows, ensuring visibility of the new CI pipelines. (`README.md`, [README.mdR39-R53](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R39-R53))
> Add scheduled dev and master builds to QML test matrix

- .github/workflows/aqt-latest-rc.yml
- .github/workflows/braket-latest-rc.yml
- .github/workflows/cirq-latest-latest.yml
- .github/workflows/cirq-latest-rc.yml
- .github/workflows/cirq-latest-stable.yml
- .github/workflows/cirq-stable-latest.yml
- .github/workflows/cirq-stable-stable.yml
- .github/workflows/ionq-latest-rc.yml
- .github/workflows/lightning-latest-rc.yml
- .github/workflows/qiskit-latest-rc.yml
- .github/workflows/qulacs-latest-rc.yml
- workflow-template-release-candidate.yml
07-04-25: ~~NOTE: CI is failing since the RC branch won't be created until next week (I'm just following the guide's timeline 🤣 ).~~ 
07-07-25: rc branches were created.
This PR was generated with the following steps,
1. Manually update `workflow-template-release-candidate.yml`
2. Use `python compile.py` to automatically change remaining workflows
3. Manually update `lightning-latest.yml`
⚠️  Some `cirq` files that are not related to `rc` were changed. This is due to a temporary patch we did last release where we tested all of `cirq` against `3.11`.
[sc-94459]
> Prepare feature freeze test matrix

- .github/workflows/lightning-latest-rc.yml
Getting [failures](https://github.com/PennyLaneAI/plugin-test-matrix/actions/workflows/lightning-latest-rc.yml) in the Feature Freeze testing matrix for lightning `latest-rc`. Adding `pytest-rng` support should fix it!
> Fix `lightning-latest-rc` on FF testing matrix

- .github/workflows/aqt-latest-latest.yml
- .github/workflows/aqt-stable-latest.yml
- .github/workflows/cirq-latest-latest.yml
- .github/workflows/cirq-stable-latest.yml
- .github/workflows/ionq-latest-latest.yml
- .github/workflows/ionq-stable-latest.yml
- .github/workflows/qiskit-latest-latest.yml
- .github/workflows/qiskit-stable-latest.yml
- .github/workflows/qulacs-latest-latest.yml
- .github/workflows/qulacs-stable-latest.yml
- README.md
- workflow-template-latest.yml
https://github.com/PennyLaneAI/pennylane/pull/7874 removed top level access to this exception. Instead it should be pulled from the `exceptions` module.
[sc-95787]
> Use new `pennylane.exceptions` module

- .github/workflows/aqt-latest-rc.yml
- .github/workflows/braket-latest-rc.yml
- .github/workflows/cirq-latest-rc.yml
- .github/workflows/ionq-latest-rc.yml
- .github/workflows/lightning-latest-rc.yml
- .github/workflows/qiskit-latest-rc.yml
- .github/workflows/qulacs-latest-rc.yml
- workflow-template-release-candidate.yml
10-03-25: NOTE: CI is failing since the RC branch won't be created until next week
This PR was generated with the following steps,
1. Manually update `workflow-template-release-candidate.yml` (0.42 -> 0.43)
2. Use `python compile.py` to automatically change remaining workflows
3. Manually update `lightning-latest-rc.yml`
[sc-100777]
> [v0.43 release] update rc branch version in FF plug-in test matrix
